"""Módulo de persistencia MongoDB para Chatbot RAG"""
__version__ = "0.1.0"

from mongodb.connection import MongoDBConnection
from mongodb.models import (
    MessageRole,
    ConversationMessage,
    ConversationCreate,
    ConversationDocument,
    MetricCreate,
    FeedbackCreate,
    RAGCacheEntry,
    LogEntry,
)
from mongodb.repositories.base_repository import BaseRepository
from mongodb.services import (
    ConversationService,
    MetricsService,
    FeedbackService,
    RAGCacheService,
    save_conversation,
    get_conversation,
    get_conversations_by_session,
    get_conversations_by_user,
    get_conversation_stats,
    get_daily_stats,
    search_conversations,
    record_metric,
    get_endpoint_metrics,
    get_system_health,
    record_feedback,
    get_feedback_stats,
    cache_response,
    cleanup_expired,
    get_cached_response,
    get_cache_stats,
    get_expired_entries,
)

__all__ = [
    "MongoDBConnection",
    "MessageRole",
    "ConversationMessage",
    "ConversationCreate",
    "ConversationDocument",
    "MetricCreate",
    "FeedbackCreate",
    "RAGCacheEntry",
    "LogEntry",
    "BaseRepository",
    "ConversationService",
    "MetricsService",
    "FeedbackService",
    "RAGCacheService",
    "save_conversation",
    "get_conversation",
    "get_conversations_by_session",
    "get_conversations_by_user",
    "get_conversation_stats",
    "get_daily_stats",
    "search_conversations",
    "record_metric",
    "get_endpoint_metrics",
    "get_system_health",
    "record_feedback",
    "get_feedback_stats",
    "cache_response",
    "cleanup_expired",
    "get_cached_response",
    "get_cache_stats",
    "get_expired_entries",
]
